name: Dummy AWS Secrets Check

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check AWS_ACCESS_KEY_ID
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "❌ AWS_ACCESS_KEY_ID is missing or not available"
            exit 1
          else
            echo "✅ AWS_ACCESS_KEY_ID is set"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Check AWS_SECRET_ACCESS_KEY
        run: |
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "❌ AWS_SECRET_ACCESS_KEY is missing or not available"
            exit 1
          else
            echo "✅ AWS_SECRET_ACCESS_KEY is set"
          fi
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
